--- 
jobs: 
  build-and-test: 
    executor: python/default
    steps: 
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - 
        run: 
          command: "make install"
          name: Install
      - 
        run: 
          command: "make lint"
          name: Lint
      - 
        run: 
          command: "make test"
          name: Test
orbs: 
  python: circleci/python@0.2.1
version: 2.1
workflows: 
  main: 
    jobs: 
      - build-and-test
